

name: vitalia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  font_awesome_flutter: ^10.9.1
  provider: ^6.1.5+1
  firebase_storage: ^13.0.0
  image_picker: ^1.2.0
  flutter_localization: ^0.3.3
  flutter_launcher_icons: ^0.14.4
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuration de l'icône
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo-favicon.png"  # mets ton icône ici

flutter:
  uses-material-design: true
  assets:
    - assets/images/logotransparent.png
    - assets/images/medecin.jpg
    - assets/images/hopital.jpg

# An images asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
