// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvoUyyRcc3HqkmwdjkpaP4uAIunKzfl4',
    appId: '1:61121001604:web:117918a0d60a3e55462ad1',
    messagingSenderId: '61121001604',
    projectId: 'vitaliaapp-d3e5e',
    authDomain: 'vitaliaapp-d3e5e.firebaseapp.com',
    storageBucket: 'vitaliaapp-d3e5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnQ75yFSBHpqoRYJTder66pO8DWfs_g8',
    appId: '1:61121001604:android:5ba65e78c8c4ba9d462ad1',
    messagingSenderId: '61121001604',
    projectId: 'vitaliaapp-d3e5e',
    storageBucket: 'vitaliaapp-d3e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00WKDpOqQb1XOVIJEuO7E2DzrGBB9NG4',
    appId: '1:61121001604:ios:335d31d7e18bd064462ad1',
    messagingSenderId: '61121001604',
    projectId: 'vitaliaapp-d3e5e',
    storageBucket: 'vitaliaapp-d3e5e.firebasestorage.app',
    iosBundleId: 'com.example.vitaliaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvoUyyRcc3HqkmwdjkpaP4uAIunKzfl4',
    appId: '1:61121001604:web:66abbdf525b3457d462ad1',
    messagingSenderId: '61121001604',
    projectId: 'vitaliaapp-d3e5e',
    authDomain: 'vitaliaapp-d3e5e.firebaseapp.com',
    storageBucket: 'vitaliaapp-d3e5e.firebasestorage.app',
  );
}
